#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAS_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RASDase")]
	public partial class RASbaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDegree(Degree instance);
    partial void UpdateDegree(Degree instance);
    partial void DeleteDegree(Degree instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertFaculty(Faculty instance);
    partial void UpdateFaculty(Faculty instance);
    partial void DeleteFaculty(Faculty instance);
    partial void InsertFormRequirement(FormRequirement instance);
    partial void UpdateFormRequirement(FormRequirement instance);
    partial void DeleteFormRequirement(FormRequirement instance);
    partial void InsertLogin(Login instance);
    partial void UpdateLogin(Login instance);
    partial void DeleteLogin(Login instance);
    partial void InsertProgram(Program instance);
    partial void UpdateProgram(Program instance);
    partial void DeleteProgram(Program instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTeacher(Teacher instance);
    partial void UpdateTeacher(Teacher instance);
    partial void DeleteTeacher(Teacher instance);
    partial void InsertSubject(Subject instance);
    partial void UpdateSubject(Subject instance);
    partial void DeleteSubject(Subject instance);
    partial void InsertT2(T2 instance);
    partial void UpdateT2(T2 instance);
    partial void DeleteT2(T2 instance);
    partial void InsertT3(T3 instance);
    partial void UpdateT3(T3 instance);
    partial void DeleteT3(T3 instance);
    #endregion
		
		public RASbaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RASDaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RASbaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RASbaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RASbaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RASbaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Degree> Degrees
		{
			get
			{
				return this.GetTable<Degree>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Faculty> Faculties
		{
			get
			{
				return this.GetTable<Faculty>();
			}
		}
		
		public System.Data.Linq.Table<FormRequirement> FormRequirements
		{
			get
			{
				return this.GetTable<FormRequirement>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
		
		public System.Data.Linq.Table<Program> Programs
		{
			get
			{
				return this.GetTable<Program>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<Teacher> Teachers
		{
			get
			{
				return this.GetTable<Teacher>();
			}
		}
		
		public System.Data.Linq.Table<Subject> Subjects
		{
			get
			{
				return this.GetTable<Subject>();
			}
		}
		
		public System.Data.Linq.Table<T2> T2s
		{
			get
			{
				return this.GetTable<T2>();
			}
		}
		
		public System.Data.Linq.Table<T3> T3s
		{
			get
			{
				return this.GetTable<T3>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Degree")]
	public partial class Degree : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDegree;
		
		private int _IDFacu;
		
		private string _NameDegree;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDegreeChanging(int value);
    partial void OnIDDegreeChanged();
    partial void OnIDFacuChanging(int value);
    partial void OnIDFacuChanged();
    partial void OnNameDegreeChanging(string value);
    partial void OnNameDegreeChanged();
    #endregion
		
		public Degree()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDegree", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDegree
		{
			get
			{
				return this._IDDegree;
			}
			set
			{
				if ((this._IDDegree != value))
				{
					this.OnIDDegreeChanging(value);
					this.SendPropertyChanging();
					this._IDDegree = value;
					this.SendPropertyChanged("IDDegree");
					this.OnIDDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFacu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFacu
		{
			get
			{
				return this._IDFacu;
			}
			set
			{
				if ((this._IDFacu != value))
				{
					this.OnIDFacuChanging(value);
					this.SendPropertyChanging();
					this._IDFacu = value;
					this.SendPropertyChanged("IDFacu");
					this.OnIDFacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameDegree", DbType="VarChar(200)")]
		public string NameDegree
		{
			get
			{
				return this._NameDegree;
			}
			set
			{
				if ((this._NameDegree != value))
				{
					this.OnNameDegreeChanging(value);
					this.SendPropertyChanging();
					this._NameDegree = value;
					this.SendPropertyChanged("NameDegree");
					this.OnNameDegreeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EmpID;
		
		private string _EmpName;
		
		private string _Position;
		
		private string _Phone;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpIDChanging(string value);
    partial void OnEmpIDChanged();
    partial void OnEmpNameChanging(string value);
    partial void OnEmpNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpName", DbType="VarChar(255)")]
		public string EmpName
		{
			get
			{
				return this._EmpName;
			}
			set
			{
				if ((this._EmpName != value))
				{
					this.OnEmpNameChanging(value);
					this.SendPropertyChanging();
					this._EmpName = value;
					this.SendPropertyChanged("EmpName");
					this.OnEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(255)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Faculty")]
	public partial class Faculty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFacu;
		
		private string _NameFacu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFacuChanging(int value);
    partial void OnIDFacuChanged();
    partial void OnNameFacuChanging(string value);
    partial void OnNameFacuChanged();
    #endregion
		
		public Faculty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFacu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFacu
		{
			get
			{
				return this._IDFacu;
			}
			set
			{
				if ((this._IDFacu != value))
				{
					this.OnIDFacuChanging(value);
					this.SendPropertyChanging();
					this._IDFacu = value;
					this.SendPropertyChanged("IDFacu");
					this.OnIDFacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFacu", DbType="VarChar(200)")]
		public string NameFacu
		{
			get
			{
				return this._NameFacu;
			}
			set
			{
				if ((this._NameFacu != value))
				{
					this.OnNameFacuChanging(value);
					this.SendPropertyChanging();
					this._NameFacu = value;
					this.SendPropertyChanged("NameFacu");
					this.OnNameFacuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FormRequirement")]
	public partial class FormRequirement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FormID;
		
		private string _FormNameTH;
		
		private string _FormNameEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnFormNameTHChanging(string value);
    partial void OnFormNameTHChanged();
    partial void OnFormNameENChanging(string value);
    partial void OnFormNameENChanged();
    #endregion
		
		public FormRequirement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNameTH", DbType="VarChar(512)")]
		public string FormNameTH
		{
			get
			{
				return this._FormNameTH;
			}
			set
			{
				if ((this._FormNameTH != value))
				{
					this.OnFormNameTHChanging(value);
					this.SendPropertyChanging();
					this._FormNameTH = value;
					this.SendPropertyChanged("FormNameTH");
					this.OnFormNameTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormNameEN", DbType="VarChar(512)")]
		public string FormNameEN
		{
			get
			{
				return this._FormNameEN;
			}
			set
			{
				if ((this._FormNameEN != value))
				{
					this.OnFormNameENChanging(value);
					this.SendPropertyChanging();
					this._FormNameEN = value;
					this.SendPropertyChanged("FormNameEN");
					this.OnFormNameENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
	public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private string _Class;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnClassChanging(string value);
    partial void OnClassChanged();
    #endregion
		
		public Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(10)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Class", DbType="VarChar(50)")]
		public string Class
		{
			get
			{
				return this._Class;
			}
			set
			{
				if ((this._Class != value))
				{
					this.OnClassChanging(value);
					this.SendPropertyChanging();
					this._Class = value;
					this.SendPropertyChanged("Class");
					this.OnClassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Program")]
	public partial class Program : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDProgram;
		
		private int _IDDegree;
		
		private int _IDFacu;
		
		private string _NameProgram;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDProgramChanging(int value);
    partial void OnIDProgramChanged();
    partial void OnIDDegreeChanging(int value);
    partial void OnIDDegreeChanged();
    partial void OnIDFacuChanging(int value);
    partial void OnIDFacuChanged();
    partial void OnNameProgramChanging(string value);
    partial void OnNameProgramChanged();
    #endregion
		
		public Program()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProgram", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDProgram
		{
			get
			{
				return this._IDProgram;
			}
			set
			{
				if ((this._IDProgram != value))
				{
					this.OnIDProgramChanging(value);
					this.SendPropertyChanging();
					this._IDProgram = value;
					this.SendPropertyChanged("IDProgram");
					this.OnIDProgramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDegree", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDegree
		{
			get
			{
				return this._IDDegree;
			}
			set
			{
				if ((this._IDDegree != value))
				{
					this.OnIDDegreeChanging(value);
					this.SendPropertyChanging();
					this._IDDegree = value;
					this.SendPropertyChanged("IDDegree");
					this.OnIDDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFacu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFacu
		{
			get
			{
				return this._IDFacu;
			}
			set
			{
				if ((this._IDFacu != value))
				{
					this.OnIDFacuChanging(value);
					this.SendPropertyChanging();
					this._IDFacu = value;
					this.SendPropertyChanged("IDFacu");
					this.OnIDFacuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameProgram", DbType="VarChar(200)")]
		public string NameProgram
		{
			get
			{
				return this._NameProgram;
			}
			set
			{
				if ((this._NameProgram != value))
				{
					this.OnNameProgramChanging(value);
					this.SendPropertyChanging();
					this._NameProgram = value;
					this.SendPropertyChanged("NameProgram");
					this.OnNameProgramChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Student_ID;
		
		private string _Identity_ID;
		
		private string _NameTH;
		
		private string _NameEn;
		
		private string _Faculty;
		
		private string _Program;
		
		private string _Degree;
		
		private System.Nullable<System.DateTime> _DateEntry;
		
		private string _Status;
		
		private string _Advisor;
		
		private System.Nullable<double> _Gpax;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _Place_Birth;
		
		private string _Nationality;
		
		private string _Religion;
		
		private string _Address;
		
		private string _Subdistrict;
		
		private string _District;
		
		private string _Province;
		
		private string _Postcode;
		
		private string _Phone;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_IDChanging(string value);
    partial void OnStudent_IDChanged();
    partial void OnIdentity_IDChanging(string value);
    partial void OnIdentity_IDChanged();
    partial void OnNameTHChanging(string value);
    partial void OnNameTHChanged();
    partial void OnNameEnChanging(string value);
    partial void OnNameEnChanged();
    partial void OnFacultyChanging(string value);
    partial void OnFacultyChanged();
    partial void OnProgramChanging(string value);
    partial void OnProgramChanged();
    partial void OnDegreeChanging(string value);
    partial void OnDegreeChanged();
    partial void OnDateEntryChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEntryChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnAdvisorChanging(string value);
    partial void OnAdvisorChanged();
    partial void OnGpaxChanging(System.Nullable<double> value);
    partial void OnGpaxChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnPlace_BirthChanging(string value);
    partial void OnPlace_BirthChanged();
    partial void OnNationalityChanging(string value);
    partial void OnNationalityChanged();
    partial void OnReligionChanging(string value);
    partial void OnReligionChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSubdistrictChanging(string value);
    partial void OnSubdistrictChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnProvinceChanging(string value);
    partial void OnProvinceChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Student()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_ID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Student_ID
		{
			get
			{
				return this._Student_ID;
			}
			set
			{
				if ((this._Student_ID != value))
				{
					this.OnStudent_IDChanging(value);
					this.SendPropertyChanging();
					this._Student_ID = value;
					this.SendPropertyChanged("Student_ID");
					this.OnStudent_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identity_ID", DbType="Char(13)")]
		public string Identity_ID
		{
			get
			{
				return this._Identity_ID;
			}
			set
			{
				if ((this._Identity_ID != value))
				{
					this.OnIdentity_IDChanging(value);
					this.SendPropertyChanging();
					this._Identity_ID = value;
					this.SendPropertyChanged("Identity_ID");
					this.OnIdentity_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameTH", DbType="VarChar(255)")]
		public string NameTH
		{
			get
			{
				return this._NameTH;
			}
			set
			{
				if ((this._NameTH != value))
				{
					this.OnNameTHChanging(value);
					this.SendPropertyChanging();
					this._NameTH = value;
					this.SendPropertyChanged("NameTH");
					this.OnNameTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEn", DbType="VarChar(255)")]
		public string NameEn
		{
			get
			{
				return this._NameEn;
			}
			set
			{
				if ((this._NameEn != value))
				{
					this.OnNameEnChanging(value);
					this.SendPropertyChanging();
					this._NameEn = value;
					this.SendPropertyChanged("NameEn");
					this.OnNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Faculty", DbType="VarChar(255)")]
		public string Faculty
		{
			get
			{
				return this._Faculty;
			}
			set
			{
				if ((this._Faculty != value))
				{
					this.OnFacultyChanging(value);
					this.SendPropertyChanging();
					this._Faculty = value;
					this.SendPropertyChanged("Faculty");
					this.OnFacultyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Program", DbType="VarChar(255)")]
		public string Program
		{
			get
			{
				return this._Program;
			}
			set
			{
				if ((this._Program != value))
				{
					this.OnProgramChanging(value);
					this.SendPropertyChanging();
					this._Program = value;
					this.SendPropertyChanged("Program");
					this.OnProgramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="VarChar(255)")]
		public string Degree
		{
			get
			{
				return this._Degree;
			}
			set
			{
				if ((this._Degree != value))
				{
					this.OnDegreeChanging(value);
					this.SendPropertyChanging();
					this._Degree = value;
					this.SendPropertyChanged("Degree");
					this.OnDegreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEntry", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEntry
		{
			get
			{
				return this._DateEntry;
			}
			set
			{
				if ((this._DateEntry != value))
				{
					this.OnDateEntryChanging(value);
					this.SendPropertyChanging();
					this._DateEntry = value;
					this.SendPropertyChanged("DateEntry");
					this.OnDateEntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Advisor", DbType="VarChar(255)")]
		public string Advisor
		{
			get
			{
				return this._Advisor;
			}
			set
			{
				if ((this._Advisor != value))
				{
					this.OnAdvisorChanging(value);
					this.SendPropertyChanging();
					this._Advisor = value;
					this.SendPropertyChanged("Advisor");
					this.OnAdvisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gpax", DbType="Float")]
		public System.Nullable<double> Gpax
		{
			get
			{
				return this._Gpax;
			}
			set
			{
				if ((this._Gpax != value))
				{
					this.OnGpaxChanging(value);
					this.SendPropertyChanging();
					this._Gpax = value;
					this.SendPropertyChanged("Gpax");
					this.OnGpaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Place_Birth", DbType="VarChar(50)")]
		public string Place_Birth
		{
			get
			{
				return this._Place_Birth;
			}
			set
			{
				if ((this._Place_Birth != value))
				{
					this.OnPlace_BirthChanging(value);
					this.SendPropertyChanging();
					this._Place_Birth = value;
					this.SendPropertyChanged("Place_Birth");
					this.OnPlace_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nationality", DbType="VarChar(50)")]
		public string Nationality
		{
			get
			{
				return this._Nationality;
			}
			set
			{
				if ((this._Nationality != value))
				{
					this.OnNationalityChanging(value);
					this.SendPropertyChanging();
					this._Nationality = value;
					this.SendPropertyChanged("Nationality");
					this.OnNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Religion", DbType="VarChar(50)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subdistrict", DbType="VarChar(50)")]
		public string Subdistrict
		{
			get
			{
				return this._Subdistrict;
			}
			set
			{
				if ((this._Subdistrict != value))
				{
					this.OnSubdistrictChanging(value);
					this.SendPropertyChanging();
					this._Subdistrict = value;
					this.SendPropertyChanged("Subdistrict");
					this.OnSubdistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="VarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Province", DbType="VarChar(50)")]
		public string Province
		{
			get
			{
				return this._Province;
			}
			set
			{
				if ((this._Province != value))
				{
					this.OnProvinceChanging(value);
					this.SendPropertyChanging();
					this._Province = value;
					this.SendPropertyChanged("Province");
					this.OnProvinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Char(5)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Char(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Teacher")]
	public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TeacherID;
		
		private string _TeacherName;
		
		private string _Position;
		
		private string _Phone;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeacherIDChanging(string value);
    partial void OnTeacherIDChanged();
    partial void OnTeacherNameChanging(string value);
    partial void OnTeacherNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Teacher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherName", DbType="VarChar(255)")]
		public string TeacherName
		{
			get
			{
				return this._TeacherName;
			}
			set
			{
				if ((this._TeacherName != value))
				{
					this.OnTeacherNameChanging(value);
					this.SendPropertyChanging();
					this._TeacherName = value;
					this.SendPropertyChanged("TeacherName");
					this.OnTeacherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="VarChar(255)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subject")]
	public partial class Subject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SubID;
		
		private System.Nullable<int> _Group;
		
		private string _NameSubThai;
		
		private string _NameSubEng;
		
		private System.Nullable<int> _Unit;
		
		private System.Nullable<System.DateTime> _DateMidterm;
		
		private string _TimeExamMidterm;
		
		private System.Nullable<System.DateTime> _DateFinal;
		
		private string _TimeExamFinal;
		
		private string _TeacherID;
		
		private string _CourseGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubIDChanging(string value);
    partial void OnSubIDChanged();
    partial void OnGroupChanging(System.Nullable<int> value);
    partial void OnGroupChanged();
    partial void OnNameSubThaiChanging(string value);
    partial void OnNameSubThaiChanged();
    partial void OnNameSubEngChanging(string value);
    partial void OnNameSubEngChanged();
    partial void OnUnitChanging(System.Nullable<int> value);
    partial void OnUnitChanged();
    partial void OnDateMidtermChanging(System.Nullable<System.DateTime> value);
    partial void OnDateMidtermChanged();
    partial void OnTimeExamMidtermChanging(string value);
    partial void OnTimeExamMidtermChanged();
    partial void OnDateFinalChanging(System.Nullable<System.DateTime> value);
    partial void OnDateFinalChanged();
    partial void OnTimeExamFinalChanging(string value);
    partial void OnTimeExamFinalChanged();
    partial void OnTeacherIDChanging(string value);
    partial void OnTeacherIDChanged();
    partial void OnCourseGroupChanging(string value);
    partial void OnCourseGroupChanged();
    #endregion
		
		public Subject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SubID
		{
			get
			{
				return this._SubID;
			}
			set
			{
				if ((this._SubID != value))
				{
					this.OnSubIDChanging(value);
					this.SendPropertyChanging();
					this._SubID = value;
					this.SendPropertyChanged("SubID");
					this.OnSubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="Int")]
		public System.Nullable<int> Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this.OnGroupChanging(value);
					this.SendPropertyChanging();
					this._Group = value;
					this.SendPropertyChanged("Group");
					this.OnGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameSubThai", DbType="VarChar(255)")]
		public string NameSubThai
		{
			get
			{
				return this._NameSubThai;
			}
			set
			{
				if ((this._NameSubThai != value))
				{
					this.OnNameSubThaiChanging(value);
					this.SendPropertyChanging();
					this._NameSubThai = value;
					this.SendPropertyChanged("NameSubThai");
					this.OnNameSubThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameSubEng", DbType="VarChar(255)")]
		public string NameSubEng
		{
			get
			{
				return this._NameSubEng;
			}
			set
			{
				if ((this._NameSubEng != value))
				{
					this.OnNameSubEngChanging(value);
					this.SendPropertyChanging();
					this._NameSubEng = value;
					this.SendPropertyChanged("NameSubEng");
					this.OnNameSubEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="Int")]
		public System.Nullable<int> Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateMidterm", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateMidterm
		{
			get
			{
				return this._DateMidterm;
			}
			set
			{
				if ((this._DateMidterm != value))
				{
					this.OnDateMidtermChanging(value);
					this.SendPropertyChanging();
					this._DateMidterm = value;
					this.SendPropertyChanged("DateMidterm");
					this.OnDateMidtermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeExamMidterm", DbType="VarChar(20)")]
		public string TimeExamMidterm
		{
			get
			{
				return this._TimeExamMidterm;
			}
			set
			{
				if ((this._TimeExamMidterm != value))
				{
					this.OnTimeExamMidtermChanging(value);
					this.SendPropertyChanging();
					this._TimeExamMidterm = value;
					this.SendPropertyChanged("TimeExamMidterm");
					this.OnTimeExamMidtermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFinal", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateFinal
		{
			get
			{
				return this._DateFinal;
			}
			set
			{
				if ((this._DateFinal != value))
				{
					this.OnDateFinalChanging(value);
					this.SendPropertyChanging();
					this._DateFinal = value;
					this.SendPropertyChanged("DateFinal");
					this.OnDateFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeExamFinal", DbType="VarChar(20)")]
		public string TimeExamFinal
		{
			get
			{
				return this._TimeExamFinal;
			}
			set
			{
				if ((this._TimeExamFinal != value))
				{
					this.OnTimeExamFinalChanging(value);
					this.SendPropertyChanging();
					this._TimeExamFinal = value;
					this.SendPropertyChanged("TimeExamFinal");
					this.OnTimeExamFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeacherID", DbType="Char(10)")]
		public string TeacherID
		{
			get
			{
				return this._TeacherID;
			}
			set
			{
				if ((this._TeacherID != value))
				{
					this.OnTeacherIDChanging(value);
					this.SendPropertyChanging();
					this._TeacherID = value;
					this.SendPropertyChanged("TeacherID");
					this.OnTeacherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseGroup", DbType="VarChar(100)")]
		public string CourseGroup
		{
			get
			{
				return this._CourseGroup;
			}
			set
			{
				if ((this._CourseGroup != value))
				{
					this.OnCourseGroupChanging(value);
					this.SendPropertyChanging();
					this._CourseGroup = value;
					this.SendPropertyChanged("CourseGroup");
					this.OnCourseGroupChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T2")]
	public partial class T2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FormID;
		
		private string _IDStudent;
		
		private int _Term;
		
		private int _YearTerm;
		
		private int _T2Count;
		
		private string _Reason__;
		
		private System.Nullable<System.DateTime> _DatePay;
		
		private System.Nullable<System.DateTime> _DateEntry;
		
		private string _CommentEmp;
		
		private System.Nullable<System.DateTime> _DateCommentEmpEntry;
		
		private string _Employee;
		
		private string _Director;
		
		private System.Nullable<System.DateTime> _DateDirectorEntry;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnIDStudentChanging(string value);
    partial void OnIDStudentChanged();
    partial void OnTermChanging(int value);
    partial void OnTermChanged();
    partial void OnYearTermChanging(int value);
    partial void OnYearTermChanged();
    partial void OnT2CountChanging(int value);
    partial void OnT2CountChanged();
    partial void OnReason__Changing(string value);
    partial void OnReason__Changed();
    partial void OnDatePayChanging(System.Nullable<System.DateTime> value);
    partial void OnDatePayChanged();
    partial void OnDateEntryChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEntryChanged();
    partial void OnCommentEmpChanging(string value);
    partial void OnCommentEmpChanged();
    partial void OnDateCommentEmpEntryChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCommentEmpEntryChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnDirectorChanging(string value);
    partial void OnDirectorChanged();
    partial void OnDateDirectorEntryChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDirectorEntryChanged();
    #endregion
		
		public T2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStudent", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDStudent
		{
			get
			{
				return this._IDStudent;
			}
			set
			{
				if ((this._IDStudent != value))
				{
					this.OnIDStudentChanging(value);
					this.SendPropertyChanging();
					this._IDStudent = value;
					this.SendPropertyChanged("IDStudent");
					this.OnIDStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Term", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Term
		{
			get
			{
				return this._Term;
			}
			set
			{
				if ((this._Term != value))
				{
					this.OnTermChanging(value);
					this.SendPropertyChanging();
					this._Term = value;
					this.SendPropertyChanged("Term");
					this.OnTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearTerm", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int YearTerm
		{
			get
			{
				return this._YearTerm;
			}
			set
			{
				if ((this._YearTerm != value))
				{
					this.OnYearTermChanging(value);
					this.SendPropertyChanging();
					this._YearTerm = value;
					this.SendPropertyChanged("YearTerm");
					this.OnYearTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T2Count", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int T2Count
		{
			get
			{
				return this._T2Count;
			}
			set
			{
				if ((this._T2Count != value))
				{
					this.OnT2CountChanging(value);
					this.SendPropertyChanging();
					this._T2Count = value;
					this.SendPropertyChanged("T2Count");
					this.OnT2CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Reason\r\n]", Storage="_Reason__", DbType="VarChar(255)")]
		public string Reason__
		{
			get
			{
				return this._Reason__;
			}
			set
			{
				if ((this._Reason__ != value))
				{
					this.OnReason__Changing(value);
					this.SendPropertyChanging();
					this._Reason__ = value;
					this.SendPropertyChanged("Reason__");
					this.OnReason__Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePay", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatePay
		{
			get
			{
				return this._DatePay;
			}
			set
			{
				if ((this._DatePay != value))
				{
					this.OnDatePayChanging(value);
					this.SendPropertyChanging();
					this._DatePay = value;
					this.SendPropertyChanged("DatePay");
					this.OnDatePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEntry", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEntry
		{
			get
			{
				return this._DateEntry;
			}
			set
			{
				if ((this._DateEntry != value))
				{
					this.OnDateEntryChanging(value);
					this.SendPropertyChanging();
					this._DateEntry = value;
					this.SendPropertyChanged("DateEntry");
					this.OnDateEntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentEmp", DbType="VarChar(255)")]
		public string CommentEmp
		{
			get
			{
				return this._CommentEmp;
			}
			set
			{
				if ((this._CommentEmp != value))
				{
					this.OnCommentEmpChanging(value);
					this.SendPropertyChanging();
					this._CommentEmp = value;
					this.SendPropertyChanged("CommentEmp");
					this.OnCommentEmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCommentEmpEntry", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCommentEmpEntry
		{
			get
			{
				return this._DateCommentEmpEntry;
			}
			set
			{
				if ((this._DateCommentEmpEntry != value))
				{
					this.OnDateCommentEmpEntryChanging(value);
					this.SendPropertyChanging();
					this._DateCommentEmpEntry = value;
					this.SendPropertyChanged("DateCommentEmpEntry");
					this.OnDateCommentEmpEntryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee", DbType="VarChar(255)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="VarChar(255)")]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this.OnDirectorChanging(value);
					this.SendPropertyChanging();
					this._Director = value;
					this.SendPropertyChanged("Director");
					this.OnDirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDirectorEntry", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateDirectorEntry
		{
			get
			{
				return this._DateDirectorEntry;
			}
			set
			{
				if ((this._DateDirectorEntry != value))
				{
					this.OnDateDirectorEntryChanging(value);
					this.SendPropertyChanging();
					this._DateDirectorEntry = value;
					this.SendPropertyChanged("DateDirectorEntry");
					this.OnDateDirectorEntryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T3")]
	public partial class T3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FormID;
		
		private string _IDStudent;
		
		private string _Education_level;
		
		private int _T3Count;
		
		private System.Nullable<int> _Term_SUT;
		
		private string _Proxy;
		
		private string _Issuer;
		
		private System.Nullable<System.DateTime> _Card_Issuance_Date;
		
		private System.Nullable<System.DateTime> _Card_Expiration_Date;
		
		private string _Identify_ID;
		
		private string _Documents;
		
		private string _Reason;
		
		private System.Data.Linq.Binary _FileCopy;
		
		private string _Signatures_Proxies;
		
		private string _Signatures_Recipient;
		
		private string _Employee;
		
		private System.Nullable<System.DateTime> _DateEmployee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormIDChanging(string value);
    partial void OnFormIDChanged();
    partial void OnIDStudentChanging(string value);
    partial void OnIDStudentChanged();
    partial void OnEducation_levelChanging(string value);
    partial void OnEducation_levelChanged();
    partial void OnT3CountChanging(int value);
    partial void OnT3CountChanged();
    partial void OnTerm_SUTChanging(System.Nullable<int> value);
    partial void OnTerm_SUTChanged();
    partial void OnProxyChanging(string value);
    partial void OnProxyChanged();
    partial void OnIssuerChanging(string value);
    partial void OnIssuerChanged();
    partial void OnCard_Issuance_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCard_Issuance_DateChanged();
    partial void OnCard_Expiration_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCard_Expiration_DateChanged();
    partial void OnIdentify_IDChanging(string value);
    partial void OnIdentify_IDChanged();
    partial void OnDocumentsChanging(string value);
    partial void OnDocumentsChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnFileCopyChanging(System.Data.Linq.Binary value);
    partial void OnFileCopyChanged();
    partial void OnSignatures_ProxiesChanging(string value);
    partial void OnSignatures_ProxiesChanged();
    partial void OnSignatures_RecipientChanging(string value);
    partial void OnSignatures_RecipientChanged();
    partial void OnEmployeeChanging(string value);
    partial void OnEmployeeChanged();
    partial void OnDateEmployeeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateEmployeeChanged();
    #endregion
		
		public T3()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FormID
		{
			get
			{
				return this._FormID;
			}
			set
			{
				if ((this._FormID != value))
				{
					this.OnFormIDChanging(value);
					this.SendPropertyChanging();
					this._FormID = value;
					this.SendPropertyChanged("FormID");
					this.OnFormIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDStudent", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDStudent
		{
			get
			{
				return this._IDStudent;
			}
			set
			{
				if ((this._IDStudent != value))
				{
					this.OnIDStudentChanging(value);
					this.SendPropertyChanging();
					this._IDStudent = value;
					this.SendPropertyChanged("IDStudent");
					this.OnIDStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education_level", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Education_level
		{
			get
			{
				return this._Education_level;
			}
			set
			{
				if ((this._Education_level != value))
				{
					this.OnEducation_levelChanging(value);
					this.SendPropertyChanging();
					this._Education_level = value;
					this.SendPropertyChanged("Education_level");
					this.OnEducation_levelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T3Count", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int T3Count
		{
			get
			{
				return this._T3Count;
			}
			set
			{
				if ((this._T3Count != value))
				{
					this.OnT3CountChanging(value);
					this.SendPropertyChanging();
					this._T3Count = value;
					this.SendPropertyChanged("T3Count");
					this.OnT3CountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Term_SUT", DbType="Int")]
		public System.Nullable<int> Term_SUT
		{
			get
			{
				return this._Term_SUT;
			}
			set
			{
				if ((this._Term_SUT != value))
				{
					this.OnTerm_SUTChanging(value);
					this.SendPropertyChanging();
					this._Term_SUT = value;
					this.SendPropertyChanged("Term_SUT");
					this.OnTerm_SUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proxy", DbType="VarChar(255)")]
		public string Proxy
		{
			get
			{
				return this._Proxy;
			}
			set
			{
				if ((this._Proxy != value))
				{
					this.OnProxyChanging(value);
					this.SendPropertyChanging();
					this._Proxy = value;
					this.SendPropertyChanged("Proxy");
					this.OnProxyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issuer", DbType="VarChar(255)")]
		public string Issuer
		{
			get
			{
				return this._Issuer;
			}
			set
			{
				if ((this._Issuer != value))
				{
					this.OnIssuerChanging(value);
					this.SendPropertyChanging();
					this._Issuer = value;
					this.SendPropertyChanged("Issuer");
					this.OnIssuerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Issuance_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Card_Issuance_Date
		{
			get
			{
				return this._Card_Issuance_Date;
			}
			set
			{
				if ((this._Card_Issuance_Date != value))
				{
					this.OnCard_Issuance_DateChanging(value);
					this.SendPropertyChanging();
					this._Card_Issuance_Date = value;
					this.SendPropertyChanged("Card_Issuance_Date");
					this.OnCard_Issuance_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Card_Expiration_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Card_Expiration_Date
		{
			get
			{
				return this._Card_Expiration_Date;
			}
			set
			{
				if ((this._Card_Expiration_Date != value))
				{
					this.OnCard_Expiration_DateChanging(value);
					this.SendPropertyChanging();
					this._Card_Expiration_Date = value;
					this.SendPropertyChanged("Card_Expiration_Date");
					this.OnCard_Expiration_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identify_ID", DbType="Char(13)")]
		public string Identify_ID
		{
			get
			{
				return this._Identify_ID;
			}
			set
			{
				if ((this._Identify_ID != value))
				{
					this.OnIdentify_IDChanging(value);
					this.SendPropertyChanging();
					this._Identify_ID = value;
					this.SendPropertyChanged("Identify_ID");
					this.OnIdentify_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documents", DbType="VarChar(255)")]
		public string Documents
		{
			get
			{
				return this._Documents;
			}
			set
			{
				if ((this._Documents != value))
				{
					this.OnDocumentsChanging(value);
					this.SendPropertyChanging();
					this._Documents = value;
					this.SendPropertyChanged("Documents");
					this.OnDocumentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(255)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileCopy", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FileCopy
		{
			get
			{
				return this._FileCopy;
			}
			set
			{
				if ((this._FileCopy != value))
				{
					this.OnFileCopyChanging(value);
					this.SendPropertyChanging();
					this._FileCopy = value;
					this.SendPropertyChanged("FileCopy");
					this.OnFileCopyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signatures_Proxies", DbType="VarChar(255)")]
		public string Signatures_Proxies
		{
			get
			{
				return this._Signatures_Proxies;
			}
			set
			{
				if ((this._Signatures_Proxies != value))
				{
					this.OnSignatures_ProxiesChanging(value);
					this.SendPropertyChanging();
					this._Signatures_Proxies = value;
					this.SendPropertyChanged("Signatures_Proxies");
					this.OnSignatures_ProxiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signatures_Recipient", DbType="VarChar(255)")]
		public string Signatures_Recipient
		{
			get
			{
				return this._Signatures_Recipient;
			}
			set
			{
				if ((this._Signatures_Recipient != value))
				{
					this.OnSignatures_RecipientChanging(value);
					this.SendPropertyChanging();
					this._Signatures_Recipient = value;
					this.SendPropertyChanged("Signatures_Recipient");
					this.OnSignatures_RecipientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee", DbType="VarChar(255)")]
		public string Employee
		{
			get
			{
				return this._Employee;
			}
			set
			{
				if ((this._Employee != value))
				{
					this.OnEmployeeChanging(value);
					this.SendPropertyChanging();
					this._Employee = value;
					this.SendPropertyChanged("Employee");
					this.OnEmployeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEmployee", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEmployee
		{
			get
			{
				return this._DateEmployee;
			}
			set
			{
				if ((this._DateEmployee != value))
				{
					this.OnDateEmployeeChanging(value);
					this.SendPropertyChanging();
					this._DateEmployee = value;
					this.SendPropertyChanged("DateEmployee");
					this.OnDateEmployeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
